/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as abandonmentScanIntel from "../abandonmentScanIntel.js";
import type * as accessReview from "../accessReview.js";
import type * as advisoryAggregator from "../advisoryAggregator.js";
import type * as advisorySync from "../advisorySync.js";
import type * as agentCrons from "../agentCrons.js";
import type * as agentData from "../agentData.js";
import type * as agentMemory from "../agentMemory.js";
import type * as agentOrchestrator from "../agentOrchestrator.js";
import type * as agenticWorkflowIntel from "../agenticWorkflowIntel.js";
import type * as agents_blastRadiusAgent from "../agents/blastRadiusAgent.js";
import type * as agents_blueTeamAgent from "../agents/blueTeamAgent.js";
import type * as agents_exploitValidationAgent from "../agents/exploitValidationAgent.js";
import type * as agents_prGenerationAgent from "../agents/prGenerationAgent.js";
import type * as agents_promptInjectionAgent from "../agents/promptInjectionAgent.js";
import type * as agents_redTeamAgent from "../agents/redTeamAgent.js";
import type * as agents_regulatoryDriftAgent from "../agents/regulatoryDriftAgent.js";
import type * as agents_remediationAgent from "../agents/remediationAgent.js";
import type * as agents_surfaceReductionAgent from "../agents/surfaceReductionAgent.js";
import type * as aiMlSecurityDriftIntel from "../aiMlSecurityDriftIntel.js";
import type * as analyticsConsent from "../analyticsConsent.js";
import type * as apiDocs from "../apiDocs.js";
import type * as apiKeys from "../apiKeys.js";
import type * as apiSecurityDriftIntel from "../apiSecurityDriftIntel.js";
import type * as artifactRegistryDriftIntel from "../artifactRegistryDriftIntel.js";
import type * as attackPaths from "../attackPaths.js";
import type * as attackSurfaceIntel from "../attackSurfaceIntel.js";
import type * as auditLog from "../auditLog.js";
import type * as auth from "../auth.js";
import type * as authLockout from "../authLockout.js";
import type * as autoRemediationIntel from "../autoRemediationIntel.js";
import type * as azureDevOpsWebhooks from "../azureDevOpsWebhooks.js";
import type * as backupDrSecurityDriftIntel from "../backupDrSecurityDriftIntel.js";
import type * as billing from "../billing.js";
import type * as billingPortal from "../billingPortal.js";
import type * as bitbucketWebhooks from "../bitbucketWebhooks.js";
import type * as blastRadiusIntel from "../blastRadiusIntel.js";
import type * as blueAgentIntel from "../blueAgentIntel.js";
import type * as branchProtectionIntel from "../branchProtectionIntel.js";
import type * as breachIngest from "../breachIngest.js";
import type * as buildConfigIntel from "../buildConfigIntel.js";
import type * as buildkiteWebhooks from "../buildkiteWebhooks.js";
import type * as businessImpactIntel from "../businessImpactIntel.js";
import type * as certPkiDriftIntel from "../certPkiDriftIntel.js";
import type * as cfgMgmtSecurityDriftIntel from "../cfgMgmtSecurityDriftIntel.js";
import type * as checkout from "../checkout.js";
import type * as cicdPipelineSecurityDriftIntel from "../cicdPipelineSecurityDriftIntel.js";
import type * as cicdScanIntel from "../cicdScanIntel.js";
import type * as circleciWebhooks from "../circleciWebhooks.js";
import type * as cloudBlastRadiusIntel from "../cloudBlastRadiusIntel.js";
import type * as cloudSecurityDriftIntel from "../cloudSecurityDriftIntel.js";
import type * as commitMessageIntel from "../commitMessageIntel.js";
import type * as communityMarketplace from "../communityMarketplace.js";
import type * as complianceAttestationIntel from "../complianceAttestationIntel.js";
import type * as complianceEvidenceIntel from "../complianceEvidenceIntel.js";
import type * as complianceRemediationIntel from "../complianceRemediationIntel.js";
import type * as confusionAttackIntel from "../confusionAttackIntel.js";
import type * as containerHardeningDriftIntel from "../containerHardeningDriftIntel.js";
import type * as containerImageIntel from "../containerImageIntel.js";
import type * as crons from "../crons.js";
import type * as crossRepoIntel from "../crossRepoIntel.js";
import type * as cryptoWeaknessIntel from "../cryptoWeaknessIntel.js";
import type * as customPolicies from "../customPolicies.js";
import type * as cveVersionScanIntel from "../cveVersionScanIntel.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboards from "../dashboards.js";
import type * as dataPipelineDriftIntel from "../dataPipelineDriftIntel.js";
import type * as dataPrivacy from "../dataPrivacy.js";
import type * as dataRetention from "../dataRetention.js";
import type * as databaseSecurityDriftIntel from "../databaseSecurityDriftIntel.js";
import type * as datadog from "../datadog.js";
import type * as deletionPipeline from "../deletionPipeline.js";
import type * as depLockIntel from "../depLockIntel.js";
import type * as depMgrSecurityDriftIntel from "../depMgrSecurityDriftIntel.js";
import type * as dependencyUpdateIntel from "../dependencyUpdateIntel.js";
import type * as deploymentMode from "../deploymentMode.js";
import type * as devSecToolsDriftIntel from "../devSecToolsDriftIntel.js";
import type * as dnsSecurityDriftIntel from "../dnsSecurityDriftIntel.js";
import type * as driftPostureIntel from "../driftPostureIntel.js";
import type * as emailSecurityDriftIntel from "../emailSecurityDriftIntel.js";
import type * as endpointSecurityDriftIntel from "../endpointSecurityDriftIntel.js";
import type * as eolDetectionIntel from "../eolDetectionIntel.js";
import type * as epssIntel from "../epssIntel.js";
import type * as escalationIntel from "../escalationIntel.js";
import type * as events from "../events.js";
import type * as executiveReportIntel from "../executiveReportIntel.js";
import type * as exports from "../exports.js";
import type * as featureFlags from "../featureFlags.js";
import type * as findingTriage from "../findingTriage.js";
import type * as findings from "../findings.js";
import type * as gamificationIntel from "../gamificationIntel.js";
import type * as gateEnforcement from "../gateEnforcement.js";
import type * as gitIntegrityIntel from "../gitIntegrityIntel.js";
import type * as githubIntegration from "../githubIntegration.js";
import type * as githubIssues from "../githubIssues.js";
import type * as githubOAuth from "../githubOAuth.js";
import type * as githubWebhooks from "../githubWebhooks.js";
import type * as gitlabWebhooks from "../gitlabWebhooks.js";
import type * as health from "../health.js";
import type * as highRiskChangeIntel from "../highRiskChangeIntel.js";
import type * as honeypotIntel from "../honeypotIntel.js";
import type * as http from "../http.js";
import type * as iacScanIntel from "../iacScanIntel.js";
import type * as identityAccessDriftIntel from "../identityAccessDriftIntel.js";
import type * as integrationHealth from "../integrationHealth.js";
import type * as integrations from "../integrations.js";
import type * as iotEmbeddedSecurityDriftIntel from "../iotEmbeddedSecurityDriftIntel.js";
import type * as ipAllowlist from "../ipAllowlist.js";
import type * as jenkinsWebhooks from "../jenkinsWebhooks.js";
import type * as jira from "../jira.js";
import type * as jobMonitoring from "../jobMonitoring.js";
import type * as k8sAdmissionDriftIntel from "../k8sAdmissionDriftIntel.js";
import type * as learningProfileIntel from "../learningProfileIntel.js";
import type * as lib_abandonmentDetection from "../lib/abandonmentDetection.js";
import type * as lib_advisorySync from "../lib/advisorySync.js";
import type * as lib_aiMlSecurityDrift from "../lib/aiMlSecurityDrift.js";
import type * as lib_apiSecurityDrift from "../lib/apiSecurityDrift.js";
import type * as lib_artifactRegistryDrift from "../lib/artifactRegistryDrift.js";
import type * as lib_attackSurface from "../lib/attackSurface.js";
import type * as lib_autoRemediation from "../lib/autoRemediation.js";
import type * as lib_backupDrSecurityDrift from "../lib/backupDrSecurityDrift.js";
import type * as lib_blastRadius from "../lib/blastRadius.js";
import type * as lib_blueAgent from "../lib/blueAgent.js";
import type * as lib_branchProtection from "../lib/branchProtection.js";
import type * as lib_breachFeeds from "../lib/breachFeeds.js";
import type * as lib_breachMatching from "../lib/breachMatching.js";
import type * as lib_buildConfigScanner from "../lib/buildConfigScanner.js";
import type * as lib_businessImpact from "../lib/businessImpact.js";
import type * as lib_certPkiDrift from "../lib/certPkiDrift.js";
import type * as lib_cfgMgmtSecurityDrift from "../lib/cfgMgmtSecurityDrift.js";
import type * as lib_cicdPipelineSecurityDrift from "../lib/cicdPipelineSecurityDrift.js";
import type * as lib_cicdSecurity from "../lib/cicdSecurity.js";
import type * as lib_cisaKev from "../lib/cisaKev.js";
import type * as lib_cloudBlastRadius from "../lib/cloudBlastRadius.js";
import type * as lib_cloudSecurityDrift from "../lib/cloudSecurityDrift.js";
import type * as lib_codeEmbedding from "../lib/codeEmbedding.js";
import type * as lib_commitMessageAnalyzer from "../lib/commitMessageAnalyzer.js";
import type * as lib_communityFingerprint from "../lib/communityFingerprint.js";
import type * as lib_complianceAttestationReport from "../lib/complianceAttestationReport.js";
import type * as lib_complianceEvidence from "../lib/complianceEvidence.js";
import type * as lib_complianceRemediationPlanner from "../lib/complianceRemediationPlanner.js";
import type * as lib_componentTrustScore from "../lib/componentTrustScore.js";
import type * as lib_confusionAttackDetection from "../lib/confusionAttackDetection.js";
import type * as lib_containerHardeningDrift from "../lib/containerHardeningDrift.js";
import type * as lib_containerImageSecurity from "../lib/containerImageSecurity.js";
import type * as lib_crossRepoImpact from "../lib/crossRepoImpact.js";
import type * as lib_cryptoWeakness from "../lib/cryptoWeakness.js";
import type * as lib_cveVersionScanner from "../lib/cveVersionScanner.js";
import type * as lib_cyclonedx from "../lib/cyclonedx.js";
import type * as lib_dataPipelineDrift from "../lib/dataPipelineDrift.js";
import type * as lib_databaseSecurityDrift from "../lib/databaseSecurityDrift.js";
import type * as lib_datadogPayload from "../lib/datadogPayload.js";
import type * as lib_depLockVerifier from "../lib/depLockVerifier.js";
import type * as lib_depMgrSecurityDrift from "../lib/depMgrSecurityDrift.js";
import type * as lib_dependencyUpdateRecommendation from "../lib/dependencyUpdateRecommendation.js";
import type * as lib_devSecToolsDrift from "../lib/devSecToolsDrift.js";
import type * as lib_dnsSecurityDrift from "../lib/dnsSecurityDrift.js";
import type * as lib_driftPostureScore from "../lib/driftPostureScore.js";
import type * as lib_emailSecurityDrift from "../lib/emailSecurityDrift.js";
import type * as lib_endpointSecurityDrift from "../lib/endpointSecurityDrift.js";
import type * as lib_eolDetection from "../lib/eolDetection.js";
import type * as lib_epssEnrichment from "../lib/epssEnrichment.js";
import type * as lib_escalationPolicy from "../lib/escalationPolicy.js";
import type * as lib_eventRouter from "../lib/eventRouter.js";
import type * as lib_executiveReport from "../lib/executiveReport.js";
import type * as lib_exploitValidation from "../lib/exploitValidation.js";
import type * as lib_findingTriage from "../lib/findingTriage.js";
import type * as lib_gamification from "../lib/gamification.js";
import type * as lib_gatePolicy from "../lib/gatePolicy.js";
import type * as lib_gitIntegrityScanner from "../lib/gitIntegrityScanner.js";
import type * as lib_githubClient from "../lib/githubClient.js";
import type * as lib_githubIssuePayload from "../lib/githubIssuePayload.js";
import type * as lib_githubWebhooks from "../lib/githubWebhooks.js";
import type * as lib_highRiskChangeDetector from "../lib/highRiskChangeDetector.js";
import type * as lib_honeypotInjector from "../lib/honeypotInjector.js";
import type * as lib_huggingFaceEnrichment from "../lib/huggingFaceEnrichment.js";
import type * as lib_iacSecurity from "../lib/iacSecurity.js";
import type * as lib_identityAccessDrift from "../lib/identityAccessDrift.js";
import type * as lib_iotEmbeddedSecurityDrift from "../lib/iotEmbeddedSecurityDrift.js";
import type * as lib_k8sAdmissionDrift from "../lib/k8sAdmissionDrift.js";
import type * as lib_learningLoop from "../lib/learningLoop.js";
import type * as lib_licenseCompliance from "../lib/licenseCompliance.js";
import type * as lib_licenseComplianceScanner from "../lib/licenseComplianceScanner.js";
import type * as lib_llmCertification from "../lib/llmCertification.js";
import type * as lib_llmClient from "../lib/llmClient.js";
import type * as lib_maliciousPackageDetection from "../lib/maliciousPackageDetection.js";
import type * as lib_memoryController from "../lib/memoryController.js";
import type * as lib_messagingSecurityDrift from "../lib/messagingSecurityDrift.js";
import type * as lib_mlAiPlatformDrift from "../lib/mlAiPlatformDrift.js";
import type * as lib_mobileAppSecurityDrift from "../lib/mobileAppSecurityDrift.js";
import type * as lib_modelProvenance from "../lib/modelProvenance.js";
import type * as lib_modelSupplyChain from "../lib/modelSupplyChain.js";
import type * as lib_networkFirewallDrift from "../lib/networkFirewallDrift.js";
import type * as lib_networkMonitoringDrift from "../lib/networkMonitoringDrift.js";
import type * as lib_observabilitySecurityDrift from "../lib/observabilitySecurityDrift.js";
import type * as lib_opsgeniePayload from "../lib/opsgeniePayload.js";
import type * as lib_osSecurityHardeningDrift from "../lib/osSecurityHardeningDrift.js";
import type * as lib_piiMasker from "../lib/piiMasker.js";
import type * as lib_prGeneration from "../lib/prGeneration.js";
import type * as lib_prometheusMetrics from "../lib/prometheusMetrics.js";
import type * as lib_promptInjection from "../lib/promptInjection.js";
import type * as lib_redAgentEscalator from "../lib/redAgentEscalator.js";
import type * as lib_redBlueSimulator from "../lib/redBlueSimulator.js";
import type * as lib_regulatoryDrift from "../lib/regulatoryDrift.js";
import type * as lib_remediationPriority from "../lib/remediationPriority.js";
import type * as lib_repositoryHealthScore from "../lib/repositoryHealthScore.js";
import type * as lib_riskAcceptance from "../lib/riskAcceptance.js";
import type * as lib_runtimeSecurityDrift from "../lib/runtimeSecurityDrift.js";
import type * as lib_sbomAttestation from "../lib/sbomAttestation.js";
import type * as lib_sbomDiff from "../lib/sbomDiff.js";
import type * as lib_sbomQuality from "../lib/sbomQuality.js";
import type * as lib_secretDetection from "../lib/secretDetection.js";
import type * as lib_secretMgmtDrift from "../lib/secretMgmtDrift.js";
import type * as lib_securityConfigDrift from "../lib/securityConfigDrift.js";
import type * as lib_securityDebtVelocity from "../lib/securityDebtVelocity.js";
import type * as lib_securityMaturityModel from "../lib/securityMaturityModel.js";
import type * as lib_securityPosture from "../lib/securityPosture.js";
import type * as lib_securityTimeline from "../lib/securityTimeline.js";
import type * as lib_semanticFingerprint from "../lib/semanticFingerprint.js";
import type * as lib_sensitiveFileDetector from "../lib/sensitiveFileDetector.js";
import type * as lib_serverlessFaasDrift from "../lib/serverlessFaasDrift.js";
import type * as lib_serviceMeshSecurityDrift from "../lib/serviceMeshSecurityDrift.js";
import type * as lib_sessionAuth from "../lib/sessionAuth.js";
import type * as lib_siemExport from "../lib/siemExport.js";
import type * as lib_siemSecurityDrift from "../lib/siemSecurityDrift.js";
import type * as lib_slaPolicy from "../lib/slaPolicy.js";
import type * as lib_spdx from "../lib/spdx.js";
import type * as lib_ssoProviderDrift from "../lib/ssoProviderDrift.js";
import type * as lib_storageDataSecurityDrift from "../lib/storageDataSecurityDrift.js";
import type * as lib_supplyChainAttestationDrift from "../lib/supplyChainAttestationDrift.js";
import type * as lib_supplyChainIntel from "../lib/supplyChainIntel.js";
import type * as lib_supplyChainPostureScorer from "../lib/supplyChainPostureScorer.js";
import type * as lib_teamsCards from "../lib/teamsCards.js";
import type * as lib_telegramIntel from "../lib/telegramIntel.js";
import type * as lib_testCoverageGap from "../lib/testCoverageGap.js";
import type * as lib_trafficAnomaly from "../lib/trafficAnomaly.js";
import type * as lib_trustScore from "../lib/trustScore.js";
import type * as lib_virtualizationSecurityDrift from "../lib/virtualizationSecurityDrift.js";
import type * as lib_voipSecurityDrift from "../lib/voipSecurityDrift.js";
import type * as lib_vpnRemoteAccessDrift from "../lib/vpnRemoteAccessDrift.js";
import type * as lib_vulnerabilityPatternLibrary from "../lib/vulnerabilityPatternLibrary.js";
import type * as lib_webServerSecurityDrift from "../lib/webServerSecurityDrift.js";
import type * as lib_webhookDispatcher from "../lib/webhookDispatcher.js";
import type * as lib_wirelessRadiusDrift from "../lib/wirelessRadiusDrift.js";
import type * as lib_zeroDayAnomaly from "../lib/zeroDayAnomaly.js";
import type * as lib_zeroDayDetector from "../lib/zeroDayDetector.js";
import type * as licenseComplianceIntel from "../licenseComplianceIntel.js";
import type * as licenseScanIntel from "../licenseScanIntel.js";
import type * as linear from "../linear.js";
import type * as llmCertificationIntel from "../llmCertificationIntel.js";
import type * as maliciousPackageIntel from "../maliciousPackageIntel.js";
import type * as maturityAssessmentIntel from "../maturityAssessmentIntel.js";
import type * as messagingSecurityDriftIntel from "../messagingSecurityDriftIntel.js";
import type * as migrations from "../migrations.js";
import type * as mlAiPlatformDriftIntel from "../mlAiPlatformDriftIntel.js";
import type * as mobileAppSecurityDriftIntel from "../mobileAppSecurityDriftIntel.js";
import type * as modelProvenanceIntel from "../modelProvenanceIntel.js";
import type * as modelSupplyChainIntel from "../modelSupplyChainIntel.js";
import type * as mssp from "../mssp.js";
import type * as msspApiKeys from "../msspApiKeys.js";
import type * as networkFirewallDriftIntel from "../networkFirewallDriftIntel.js";
import type * as networkMonitoringDriftIntel from "../networkMonitoringDriftIntel.js";
import type * as neuralMemory from "../neuralMemory.js";
import type * as neuralMemoryScheduler from "../neuralMemoryScheduler.js";
import type * as notifications from "../notifications.js";
import type * as observabilityIntel from "../observabilityIntel.js";
import type * as observabilitySecurityDriftIntel from "../observabilitySecurityDriftIntel.js";
import type * as onCall from "../onCall.js";
import type * as onboarding from "../onboarding.js";
import type * as opsgenie from "../opsgenie.js";
import type * as osSecurityHardeningDriftIntel from "../osSecurityHardeningDriftIntel.js";
import type * as outgoingWebhooks from "../outgoingWebhooks.js";
import type * as pagerduty from "../pagerduty.js";
import type * as plans from "../plans.js";
import type * as postFixValidation from "../postFixValidation.js";
import type * as prGeneration from "../prGeneration.js";
import type * as promptIntelligence from "../promptIntelligence.js";
import type * as rbac from "../rbac.js";
import type * as redAgentEscalation from "../redAgentEscalation.js";
import type * as redBlueIntel from "../redBlueIntel.js";
import type * as regulatoryDriftIntel from "../regulatoryDriftIntel.js";
import type * as remediationPlaybooks from "../remediationPlaybooks.js";
import type * as remediationQueueIntel from "../remediationQueueIntel.js";
import type * as reports from "../reports.js";
import type * as repositories from "../repositories.js";
import type * as repositoryHealthIntel from "../repositoryHealthIntel.js";
import type * as retention from "../retention.js";
import type * as riskAcceptanceIntel from "../riskAcceptanceIntel.js";
import type * as runtimeSecurityDriftIntel from "../runtimeSecurityDriftIntel.js";
import type * as sandboxValidation from "../sandboxValidation.js";
import type * as sbom from "../sbom.js";
import type * as sbomAttestationIntel from "../sbomAttestationIntel.js";
import type * as sbomQualityIntel from "../sbomQualityIntel.js";
import type * as scanScheduling from "../scanScheduling.js";
import type * as search from "../search.js";
import type * as secretDetectionIntel from "../secretDetectionIntel.js";
import type * as secretMgmtDriftIntel from "../secretMgmtDriftIntel.js";
import type * as securityConfigDriftIntel from "../securityConfigDriftIntel.js";
import type * as securityDebtIntel from "../securityDebtIntel.js";
import type * as securityEducation from "../securityEducation.js";
import type * as securityPosture from "../securityPosture.js";
import type * as securityTimelineIntel from "../securityTimelineIntel.js";
import type * as seed from "../seed.js";
import type * as semanticFingerprintIntel from "../semanticFingerprintIntel.js";
import type * as sensitiveFileIntel from "../sensitiveFileIntel.js";
import type * as serverlessFaasDriftIntel from "../serverlessFaasDriftIntel.js";
import type * as serviceMeshSecurityDriftIntel from "../serviceMeshSecurityDriftIntel.js";
import type * as sessionManagement from "../sessionManagement.js";
import type * as shortcut from "../shortcut.js";
import type * as siemIntel from "../siemIntel.js";
import type * as siemSecurityDriftIntel from "../siemSecurityDriftIntel.js";
import type * as slaIntel from "../slaIntel.js";
import type * as slack from "../slack.js";
import type * as sso from "../sso.js";
import type * as ssoProviderDriftIntel from "../ssoProviderDriftIntel.js";
import type * as storageDataSecurityDriftIntel from "../storageDataSecurityDriftIntel.js";
import type * as stripeWebhook from "../stripeWebhook.js";
import type * as supplyChainAttestationDriftIntel from "../supplyChainAttestationDriftIntel.js";
import type * as supplyChainMonitor from "../supplyChainMonitor.js";
import type * as supplyChainPostureIntel from "../supplyChainPostureIntel.js";
import type * as suppressionRules from "../suppressionRules.js";
import type * as teams from "../teams.js";
import type * as testCoverageGapIntel from "../testCoverageGapIntel.js";
import type * as threatIntelligence from "../threatIntelligence.js";
import type * as tier2BreachFeeds from "../tier2BreachFeeds.js";
import type * as tier3BreachFeeds from "../tier3BreachFeeds.js";
import type * as tier3Intel from "../tier3Intel.js";
import type * as trafficAnomalyIntel from "../trafficAnomalyIntel.js";
import type * as trustScoreIntel from "../trustScoreIntel.js";
import type * as twoFactor from "../twoFactor.js";
import type * as usage from "../usage.js";
import type * as userProfile from "../userProfile.js";
import type * as vendorTrust from "../vendorTrust.js";
import type * as virtualizationSecurityDriftIntel from "../virtualizationSecurityDriftIntel.js";
import type * as voipSecurityDriftIntel from "../voipSecurityDriftIntel.js";
import type * as vpnRemoteAccessDriftIntel from "../vpnRemoteAccessDriftIntel.js";
import type * as webServerSecurityDriftIntel from "../webServerSecurityDriftIntel.js";
import type * as webhooks from "../webhooks.js";
import type * as wirelessRadiusDriftIntel from "../wirelessRadiusDriftIntel.js";
import type * as workspaceAuth from "../workspaceAuth.js";
import type * as zeroDayDetectionIntel from "../zeroDayDetectionIntel.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  abandonmentScanIntel: typeof abandonmentScanIntel;
  accessReview: typeof accessReview;
  advisoryAggregator: typeof advisoryAggregator;
  advisorySync: typeof advisorySync;
  agentCrons: typeof agentCrons;
  agentData: typeof agentData;
  agentMemory: typeof agentMemory;
  agentOrchestrator: typeof agentOrchestrator;
  agenticWorkflowIntel: typeof agenticWorkflowIntel;
  "agents/blastRadiusAgent": typeof agents_blastRadiusAgent;
  "agents/blueTeamAgent": typeof agents_blueTeamAgent;
  "agents/exploitValidationAgent": typeof agents_exploitValidationAgent;
  "agents/prGenerationAgent": typeof agents_prGenerationAgent;
  "agents/promptInjectionAgent": typeof agents_promptInjectionAgent;
  "agents/redTeamAgent": typeof agents_redTeamAgent;
  "agents/regulatoryDriftAgent": typeof agents_regulatoryDriftAgent;
  "agents/remediationAgent": typeof agents_remediationAgent;
  "agents/surfaceReductionAgent": typeof agents_surfaceReductionAgent;
  aiMlSecurityDriftIntel: typeof aiMlSecurityDriftIntel;
  analyticsConsent: typeof analyticsConsent;
  apiDocs: typeof apiDocs;
  apiKeys: typeof apiKeys;
  apiSecurityDriftIntel: typeof apiSecurityDriftIntel;
  artifactRegistryDriftIntel: typeof artifactRegistryDriftIntel;
  attackPaths: typeof attackPaths;
  attackSurfaceIntel: typeof attackSurfaceIntel;
  auditLog: typeof auditLog;
  auth: typeof auth;
  authLockout: typeof authLockout;
  autoRemediationIntel: typeof autoRemediationIntel;
  azureDevOpsWebhooks: typeof azureDevOpsWebhooks;
  backupDrSecurityDriftIntel: typeof backupDrSecurityDriftIntel;
  billing: typeof billing;
  billingPortal: typeof billingPortal;
  bitbucketWebhooks: typeof bitbucketWebhooks;
  blastRadiusIntel: typeof blastRadiusIntel;
  blueAgentIntel: typeof blueAgentIntel;
  branchProtectionIntel: typeof branchProtectionIntel;
  breachIngest: typeof breachIngest;
  buildConfigIntel: typeof buildConfigIntel;
  buildkiteWebhooks: typeof buildkiteWebhooks;
  businessImpactIntel: typeof businessImpactIntel;
  certPkiDriftIntel: typeof certPkiDriftIntel;
  cfgMgmtSecurityDriftIntel: typeof cfgMgmtSecurityDriftIntel;
  checkout: typeof checkout;
  cicdPipelineSecurityDriftIntel: typeof cicdPipelineSecurityDriftIntel;
  cicdScanIntel: typeof cicdScanIntel;
  circleciWebhooks: typeof circleciWebhooks;
  cloudBlastRadiusIntel: typeof cloudBlastRadiusIntel;
  cloudSecurityDriftIntel: typeof cloudSecurityDriftIntel;
  commitMessageIntel: typeof commitMessageIntel;
  communityMarketplace: typeof communityMarketplace;
  complianceAttestationIntel: typeof complianceAttestationIntel;
  complianceEvidenceIntel: typeof complianceEvidenceIntel;
  complianceRemediationIntel: typeof complianceRemediationIntel;
  confusionAttackIntel: typeof confusionAttackIntel;
  containerHardeningDriftIntel: typeof containerHardeningDriftIntel;
  containerImageIntel: typeof containerImageIntel;
  crons: typeof crons;
  crossRepoIntel: typeof crossRepoIntel;
  cryptoWeaknessIntel: typeof cryptoWeaknessIntel;
  customPolicies: typeof customPolicies;
  cveVersionScanIntel: typeof cveVersionScanIntel;
  dashboard: typeof dashboard;
  dashboards: typeof dashboards;
  dataPipelineDriftIntel: typeof dataPipelineDriftIntel;
  dataPrivacy: typeof dataPrivacy;
  dataRetention: typeof dataRetention;
  databaseSecurityDriftIntel: typeof databaseSecurityDriftIntel;
  datadog: typeof datadog;
  deletionPipeline: typeof deletionPipeline;
  depLockIntel: typeof depLockIntel;
  depMgrSecurityDriftIntel: typeof depMgrSecurityDriftIntel;
  dependencyUpdateIntel: typeof dependencyUpdateIntel;
  deploymentMode: typeof deploymentMode;
  devSecToolsDriftIntel: typeof devSecToolsDriftIntel;
  dnsSecurityDriftIntel: typeof dnsSecurityDriftIntel;
  driftPostureIntel: typeof driftPostureIntel;
  emailSecurityDriftIntel: typeof emailSecurityDriftIntel;
  endpointSecurityDriftIntel: typeof endpointSecurityDriftIntel;
  eolDetectionIntel: typeof eolDetectionIntel;
  epssIntel: typeof epssIntel;
  escalationIntel: typeof escalationIntel;
  events: typeof events;
  executiveReportIntel: typeof executiveReportIntel;
  exports: typeof exports;
  featureFlags: typeof featureFlags;
  findingTriage: typeof findingTriage;
  findings: typeof findings;
  gamificationIntel: typeof gamificationIntel;
  gateEnforcement: typeof gateEnforcement;
  gitIntegrityIntel: typeof gitIntegrityIntel;
  githubIntegration: typeof githubIntegration;
  githubIssues: typeof githubIssues;
  githubOAuth: typeof githubOAuth;
  githubWebhooks: typeof githubWebhooks;
  gitlabWebhooks: typeof gitlabWebhooks;
  health: typeof health;
  highRiskChangeIntel: typeof highRiskChangeIntel;
  honeypotIntel: typeof honeypotIntel;
  http: typeof http;
  iacScanIntel: typeof iacScanIntel;
  identityAccessDriftIntel: typeof identityAccessDriftIntel;
  integrationHealth: typeof integrationHealth;
  integrations: typeof integrations;
  iotEmbeddedSecurityDriftIntel: typeof iotEmbeddedSecurityDriftIntel;
  ipAllowlist: typeof ipAllowlist;
  jenkinsWebhooks: typeof jenkinsWebhooks;
  jira: typeof jira;
  jobMonitoring: typeof jobMonitoring;
  k8sAdmissionDriftIntel: typeof k8sAdmissionDriftIntel;
  learningProfileIntel: typeof learningProfileIntel;
  "lib/abandonmentDetection": typeof lib_abandonmentDetection;
  "lib/advisorySync": typeof lib_advisorySync;
  "lib/aiMlSecurityDrift": typeof lib_aiMlSecurityDrift;
  "lib/apiSecurityDrift": typeof lib_apiSecurityDrift;
  "lib/artifactRegistryDrift": typeof lib_artifactRegistryDrift;
  "lib/attackSurface": typeof lib_attackSurface;
  "lib/autoRemediation": typeof lib_autoRemediation;
  "lib/backupDrSecurityDrift": typeof lib_backupDrSecurityDrift;
  "lib/blastRadius": typeof lib_blastRadius;
  "lib/blueAgent": typeof lib_blueAgent;
  "lib/branchProtection": typeof lib_branchProtection;
  "lib/breachFeeds": typeof lib_breachFeeds;
  "lib/breachMatching": typeof lib_breachMatching;
  "lib/buildConfigScanner": typeof lib_buildConfigScanner;
  "lib/businessImpact": typeof lib_businessImpact;
  "lib/certPkiDrift": typeof lib_certPkiDrift;
  "lib/cfgMgmtSecurityDrift": typeof lib_cfgMgmtSecurityDrift;
  "lib/cicdPipelineSecurityDrift": typeof lib_cicdPipelineSecurityDrift;
  "lib/cicdSecurity": typeof lib_cicdSecurity;
  "lib/cisaKev": typeof lib_cisaKev;
  "lib/cloudBlastRadius": typeof lib_cloudBlastRadius;
  "lib/cloudSecurityDrift": typeof lib_cloudSecurityDrift;
  "lib/codeEmbedding": typeof lib_codeEmbedding;
  "lib/commitMessageAnalyzer": typeof lib_commitMessageAnalyzer;
  "lib/communityFingerprint": typeof lib_communityFingerprint;
  "lib/complianceAttestationReport": typeof lib_complianceAttestationReport;
  "lib/complianceEvidence": typeof lib_complianceEvidence;
  "lib/complianceRemediationPlanner": typeof lib_complianceRemediationPlanner;
  "lib/componentTrustScore": typeof lib_componentTrustScore;
  "lib/confusionAttackDetection": typeof lib_confusionAttackDetection;
  "lib/containerHardeningDrift": typeof lib_containerHardeningDrift;
  "lib/containerImageSecurity": typeof lib_containerImageSecurity;
  "lib/crossRepoImpact": typeof lib_crossRepoImpact;
  "lib/cryptoWeakness": typeof lib_cryptoWeakness;
  "lib/cveVersionScanner": typeof lib_cveVersionScanner;
  "lib/cyclonedx": typeof lib_cyclonedx;
  "lib/dataPipelineDrift": typeof lib_dataPipelineDrift;
  "lib/databaseSecurityDrift": typeof lib_databaseSecurityDrift;
  "lib/datadogPayload": typeof lib_datadogPayload;
  "lib/depLockVerifier": typeof lib_depLockVerifier;
  "lib/depMgrSecurityDrift": typeof lib_depMgrSecurityDrift;
  "lib/dependencyUpdateRecommendation": typeof lib_dependencyUpdateRecommendation;
  "lib/devSecToolsDrift": typeof lib_devSecToolsDrift;
  "lib/dnsSecurityDrift": typeof lib_dnsSecurityDrift;
  "lib/driftPostureScore": typeof lib_driftPostureScore;
  "lib/emailSecurityDrift": typeof lib_emailSecurityDrift;
  "lib/endpointSecurityDrift": typeof lib_endpointSecurityDrift;
  "lib/eolDetection": typeof lib_eolDetection;
  "lib/epssEnrichment": typeof lib_epssEnrichment;
  "lib/escalationPolicy": typeof lib_escalationPolicy;
  "lib/eventRouter": typeof lib_eventRouter;
  "lib/executiveReport": typeof lib_executiveReport;
  "lib/exploitValidation": typeof lib_exploitValidation;
  "lib/findingTriage": typeof lib_findingTriage;
  "lib/gamification": typeof lib_gamification;
  "lib/gatePolicy": typeof lib_gatePolicy;
  "lib/gitIntegrityScanner": typeof lib_gitIntegrityScanner;
  "lib/githubClient": typeof lib_githubClient;
  "lib/githubIssuePayload": typeof lib_githubIssuePayload;
  "lib/githubWebhooks": typeof lib_githubWebhooks;
  "lib/highRiskChangeDetector": typeof lib_highRiskChangeDetector;
  "lib/honeypotInjector": typeof lib_honeypotInjector;
  "lib/huggingFaceEnrichment": typeof lib_huggingFaceEnrichment;
  "lib/iacSecurity": typeof lib_iacSecurity;
  "lib/identityAccessDrift": typeof lib_identityAccessDrift;
  "lib/iotEmbeddedSecurityDrift": typeof lib_iotEmbeddedSecurityDrift;
  "lib/k8sAdmissionDrift": typeof lib_k8sAdmissionDrift;
  "lib/learningLoop": typeof lib_learningLoop;
  "lib/licenseCompliance": typeof lib_licenseCompliance;
  "lib/licenseComplianceScanner": typeof lib_licenseComplianceScanner;
  "lib/llmCertification": typeof lib_llmCertification;
  "lib/llmClient": typeof lib_llmClient;
  "lib/maliciousPackageDetection": typeof lib_maliciousPackageDetection;
  "lib/memoryController": typeof lib_memoryController;
  "lib/messagingSecurityDrift": typeof lib_messagingSecurityDrift;
  "lib/mlAiPlatformDrift": typeof lib_mlAiPlatformDrift;
  "lib/mobileAppSecurityDrift": typeof lib_mobileAppSecurityDrift;
  "lib/modelProvenance": typeof lib_modelProvenance;
  "lib/modelSupplyChain": typeof lib_modelSupplyChain;
  "lib/networkFirewallDrift": typeof lib_networkFirewallDrift;
  "lib/networkMonitoringDrift": typeof lib_networkMonitoringDrift;
  "lib/observabilitySecurityDrift": typeof lib_observabilitySecurityDrift;
  "lib/opsgeniePayload": typeof lib_opsgeniePayload;
  "lib/osSecurityHardeningDrift": typeof lib_osSecurityHardeningDrift;
  "lib/piiMasker": typeof lib_piiMasker;
  "lib/prGeneration": typeof lib_prGeneration;
  "lib/prometheusMetrics": typeof lib_prometheusMetrics;
  "lib/promptInjection": typeof lib_promptInjection;
  "lib/redAgentEscalator": typeof lib_redAgentEscalator;
  "lib/redBlueSimulator": typeof lib_redBlueSimulator;
  "lib/regulatoryDrift": typeof lib_regulatoryDrift;
  "lib/remediationPriority": typeof lib_remediationPriority;
  "lib/repositoryHealthScore": typeof lib_repositoryHealthScore;
  "lib/riskAcceptance": typeof lib_riskAcceptance;
  "lib/runtimeSecurityDrift": typeof lib_runtimeSecurityDrift;
  "lib/sbomAttestation": typeof lib_sbomAttestation;
  "lib/sbomDiff": typeof lib_sbomDiff;
  "lib/sbomQuality": typeof lib_sbomQuality;
  "lib/secretDetection": typeof lib_secretDetection;
  "lib/secretMgmtDrift": typeof lib_secretMgmtDrift;
  "lib/securityConfigDrift": typeof lib_securityConfigDrift;
  "lib/securityDebtVelocity": typeof lib_securityDebtVelocity;
  "lib/securityMaturityModel": typeof lib_securityMaturityModel;
  "lib/securityPosture": typeof lib_securityPosture;
  "lib/securityTimeline": typeof lib_securityTimeline;
  "lib/semanticFingerprint": typeof lib_semanticFingerprint;
  "lib/sensitiveFileDetector": typeof lib_sensitiveFileDetector;
  "lib/serverlessFaasDrift": typeof lib_serverlessFaasDrift;
  "lib/serviceMeshSecurityDrift": typeof lib_serviceMeshSecurityDrift;
  "lib/sessionAuth": typeof lib_sessionAuth;
  "lib/siemExport": typeof lib_siemExport;
  "lib/siemSecurityDrift": typeof lib_siemSecurityDrift;
  "lib/slaPolicy": typeof lib_slaPolicy;
  "lib/spdx": typeof lib_spdx;
  "lib/ssoProviderDrift": typeof lib_ssoProviderDrift;
  "lib/storageDataSecurityDrift": typeof lib_storageDataSecurityDrift;
  "lib/supplyChainAttestationDrift": typeof lib_supplyChainAttestationDrift;
  "lib/supplyChainIntel": typeof lib_supplyChainIntel;
  "lib/supplyChainPostureScorer": typeof lib_supplyChainPostureScorer;
  "lib/teamsCards": typeof lib_teamsCards;
  "lib/telegramIntel": typeof lib_telegramIntel;
  "lib/testCoverageGap": typeof lib_testCoverageGap;
  "lib/trafficAnomaly": typeof lib_trafficAnomaly;
  "lib/trustScore": typeof lib_trustScore;
  "lib/virtualizationSecurityDrift": typeof lib_virtualizationSecurityDrift;
  "lib/voipSecurityDrift": typeof lib_voipSecurityDrift;
  "lib/vpnRemoteAccessDrift": typeof lib_vpnRemoteAccessDrift;
  "lib/vulnerabilityPatternLibrary": typeof lib_vulnerabilityPatternLibrary;
  "lib/webServerSecurityDrift": typeof lib_webServerSecurityDrift;
  "lib/webhookDispatcher": typeof lib_webhookDispatcher;
  "lib/wirelessRadiusDrift": typeof lib_wirelessRadiusDrift;
  "lib/zeroDayAnomaly": typeof lib_zeroDayAnomaly;
  "lib/zeroDayDetector": typeof lib_zeroDayDetector;
  licenseComplianceIntel: typeof licenseComplianceIntel;
  licenseScanIntel: typeof licenseScanIntel;
  linear: typeof linear;
  llmCertificationIntel: typeof llmCertificationIntel;
  maliciousPackageIntel: typeof maliciousPackageIntel;
  maturityAssessmentIntel: typeof maturityAssessmentIntel;
  messagingSecurityDriftIntel: typeof messagingSecurityDriftIntel;
  migrations: typeof migrations;
  mlAiPlatformDriftIntel: typeof mlAiPlatformDriftIntel;
  mobileAppSecurityDriftIntel: typeof mobileAppSecurityDriftIntel;
  modelProvenanceIntel: typeof modelProvenanceIntel;
  modelSupplyChainIntel: typeof modelSupplyChainIntel;
  mssp: typeof mssp;
  msspApiKeys: typeof msspApiKeys;
  networkFirewallDriftIntel: typeof networkFirewallDriftIntel;
  networkMonitoringDriftIntel: typeof networkMonitoringDriftIntel;
  neuralMemory: typeof neuralMemory;
  neuralMemoryScheduler: typeof neuralMemoryScheduler;
  notifications: typeof notifications;
  observabilityIntel: typeof observabilityIntel;
  observabilitySecurityDriftIntel: typeof observabilitySecurityDriftIntel;
  onCall: typeof onCall;
  onboarding: typeof onboarding;
  opsgenie: typeof opsgenie;
  osSecurityHardeningDriftIntel: typeof osSecurityHardeningDriftIntel;
  outgoingWebhooks: typeof outgoingWebhooks;
  pagerduty: typeof pagerduty;
  plans: typeof plans;
  postFixValidation: typeof postFixValidation;
  prGeneration: typeof prGeneration;
  promptIntelligence: typeof promptIntelligence;
  rbac: typeof rbac;
  redAgentEscalation: typeof redAgentEscalation;
  redBlueIntel: typeof redBlueIntel;
  regulatoryDriftIntel: typeof regulatoryDriftIntel;
  remediationPlaybooks: typeof remediationPlaybooks;
  remediationQueueIntel: typeof remediationQueueIntel;
  reports: typeof reports;
  repositories: typeof repositories;
  repositoryHealthIntel: typeof repositoryHealthIntel;
  retention: typeof retention;
  riskAcceptanceIntel: typeof riskAcceptanceIntel;
  runtimeSecurityDriftIntel: typeof runtimeSecurityDriftIntel;
  sandboxValidation: typeof sandboxValidation;
  sbom: typeof sbom;
  sbomAttestationIntel: typeof sbomAttestationIntel;
  sbomQualityIntel: typeof sbomQualityIntel;
  scanScheduling: typeof scanScheduling;
  search: typeof search;
  secretDetectionIntel: typeof secretDetectionIntel;
  secretMgmtDriftIntel: typeof secretMgmtDriftIntel;
  securityConfigDriftIntel: typeof securityConfigDriftIntel;
  securityDebtIntel: typeof securityDebtIntel;
  securityEducation: typeof securityEducation;
  securityPosture: typeof securityPosture;
  securityTimelineIntel: typeof securityTimelineIntel;
  seed: typeof seed;
  semanticFingerprintIntel: typeof semanticFingerprintIntel;
  sensitiveFileIntel: typeof sensitiveFileIntel;
  serverlessFaasDriftIntel: typeof serverlessFaasDriftIntel;
  serviceMeshSecurityDriftIntel: typeof serviceMeshSecurityDriftIntel;
  sessionManagement: typeof sessionManagement;
  shortcut: typeof shortcut;
  siemIntel: typeof siemIntel;
  siemSecurityDriftIntel: typeof siemSecurityDriftIntel;
  slaIntel: typeof slaIntel;
  slack: typeof slack;
  sso: typeof sso;
  ssoProviderDriftIntel: typeof ssoProviderDriftIntel;
  storageDataSecurityDriftIntel: typeof storageDataSecurityDriftIntel;
  stripeWebhook: typeof stripeWebhook;
  supplyChainAttestationDriftIntel: typeof supplyChainAttestationDriftIntel;
  supplyChainMonitor: typeof supplyChainMonitor;
  supplyChainPostureIntel: typeof supplyChainPostureIntel;
  suppressionRules: typeof suppressionRules;
  teams: typeof teams;
  testCoverageGapIntel: typeof testCoverageGapIntel;
  threatIntelligence: typeof threatIntelligence;
  tier2BreachFeeds: typeof tier2BreachFeeds;
  tier3BreachFeeds: typeof tier3BreachFeeds;
  tier3Intel: typeof tier3Intel;
  trafficAnomalyIntel: typeof trafficAnomalyIntel;
  trustScoreIntel: typeof trustScoreIntel;
  twoFactor: typeof twoFactor;
  usage: typeof usage;
  userProfile: typeof userProfile;
  vendorTrust: typeof vendorTrust;
  virtualizationSecurityDriftIntel: typeof virtualizationSecurityDriftIntel;
  voipSecurityDriftIntel: typeof voipSecurityDriftIntel;
  vpnRemoteAccessDriftIntel: typeof vpnRemoteAccessDriftIntel;
  webServerSecurityDriftIntel: typeof webServerSecurityDriftIntel;
  webhooks: typeof webhooks;
  wirelessRadiusDriftIntel: typeof wirelessRadiusDriftIntel;
  workspaceAuth: typeof workspaceAuth;
  zeroDayDetectionIntel: typeof zeroDayDetectionIntel;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
