// Pure library — zero Convex imports.
// All functions are deterministic and fully unit-testable.

// ─── Types ────────────────────────────────────────────────────────────────────

export type ComponentSnapshot = {
  name: string
  normalizedName: string
  ecosystem: string
  version: string
  isDirect: boolean
}

export type RepositorySnapshot = {
  repositoryId: string
  repositoryName: string
  components: ComponentSnapshot[]
}

export type RepositoryImpactDetail = {
  repositoryId: string
  repositoryName: string
  directMatchCount: number
  transitiveMatchCount: number
  totalMatchCount: number
  matchedVersions: string[]
  affected: boolean
}

export type CrossRepoImpactResult = {
  totalRepositories: number
  affectedRepositoryCount: number
  affectedRepositories: RepositoryImpactDetail[]
  summary: string
}

// ─── Normalization ─────────────────────────────────────────────────────────

/**
 * Normalizes a package name for cross-repository comparison.
 *
 * Rules applied (in order):
 *   1. Lowercase everything
 *   2. Strip npm @scope/ prefixes (e.g. @types/node → node)
 *   3. Collapse dashes, underscores, and dots into a single dash
 *
 * This is intentionally looser than an ecosystem-aware canonicalizer so that
 * a name change in casing or separator style still yields a match across SBOM
 * snapshots that were generated by different toolchains.
 */
export function normalizeForCrossRepo(name: string): string {
  return name
    .toLowerCase()
    .replace(/^@[\w-]+\//, '') // strip @scope/ prefix (npm scoped packages)
    .replace(/[_. ]+/g, '-') // normalise underscores, dots, spaces → dash
    .replace(/-{2,}/g, '-') // collapse consecutive dashes
    .replace(/^-|-$/g, '') // strip leading/trailing dashes
}

// ─── Package matching ──────────────────────────────────────────────────────

/**
 * Returns true when a SBOM component matches the advisory package name and
 * ecosystem.
 *
 * Ecosystem matching is intentionally permissive: if the advisory ecosystem is
 * 'unknown' we skip the ecosystem check entirely, because advisory feeds
 * sometimes omit or mis-label the ecosystem while the SBOM capture is accurate.
 */
export function matchesPackage(
  component: ComponentSnapshot,
  packageName: string,
  ecosystem: string,
): boolean {
  const normalizedQuery = normalizeForCrossRepo(packageName)
  const normalizedComponent =
    component.normalizedName.length > 0
      ? component.normalizedName.toLowerCase()
      : normalizeForCrossRepo(component.name)

  const nameMatches = normalizedComponent === normalizedQuery

  if (!nameMatches) return false

  // Skip ecosystem check when the advisory does not specify one
  if (ecosystem === 'unknown' || ecosystem === '') return true

  // Ecosystem comparison is case-insensitive but otherwise exact
  return component.ecosystem.toLowerCase() === ecosystem.toLowerCase()
}

// ─── Per-repository assessment ─────────────────────────────────────────────

/**
 * Assesses whether a single repository's SBOM snapshot contains the disclosed
 * package and, if so, how it's used (direct vs. transitive).
 */
export function assessRepositoryImpact(
  snapshot: RepositorySnapshot,
  packageName: string,
  ecosystem: string,
): RepositoryImpactDetail {
  const matching = snapshot.components.filter((c) =>
    matchesPackage(c, packageName, ecosystem),
  )

  const directMatchCount = matching.filter((c) => c.isDirect).length
  const transitiveMatchCount = matching.filter((c) => !c.isDirect).length

  // Deduplicate versions — a repo may have the same package in multiple source files
  const matchedVersions = [...new Set(matching.map((c) => c.version))].filter(
    (v) => v.length > 0,
  )

  return {
    repositoryId: snapshot.repositoryId,
    repositoryName: snapshot.repositoryName,
    directMatchCount,
    transitiveMatchCount,
    totalMatchCount: matching.length,
    matchedVersions,
    affected: matching.length > 0,
  }
}

// ─── Tenant-wide impact computation ───────────────────────────────────────

/**
 * Computes the cross-repository blast radius of a disclosed package across all
 * known repository snapshots for the tenant.
 *
 * The source repository (where the disclosure was originally matched) is
 * expected to be excluded by the caller before passing `repositorySnapshots`
 * — this function only reports lateral exposure in *other* repositories.
 */
export function computeCrossRepoImpact(args: {
  packageName: string
  ecosystem: string
  severity: string
  findingTitle: string
  repositorySnapshots: RepositorySnapshot[]
}): CrossRepoImpactResult {
  const { packageName, ecosystem, severity, repositorySnapshots } = args

  const impacts = repositorySnapshots.map((snapshot) =>
    assessRepositoryImpact(snapshot, packageName, ecosystem),
  )

  const affected = impacts.filter((i) => i.affected)

  return {
    totalRepositories: repositorySnapshots.length,
    affectedRepositoryCount: affected.length,
    affectedRepositories: affected,
    summary: buildCrossRepoSummary({
      packageName,
      severity,
      totalRepositories: repositorySnapshots.length,
      affectedRepositoryCount: affected.length,
      affectedRepositoryNames: affected.map((i) => i.repositoryName),
    }),
  }
}

// ─── Summary text ──────────────────────────────────────────────────────────

function buildCrossRepoSummary(args: {
  packageName: string
  severity: string
  totalRepositories: number
  affectedRepositoryCount: number
  affectedRepositoryNames: string[]
}): string {
  const { packageName, severity, totalRepositories, affectedRepositoryCount, affectedRepositoryNames } =
    args

  if (totalRepositories === 0) {
    return `${packageName} (${severity}) has no other monitored repositories to check for lateral exposure.`
  }

  if (affectedRepositoryCount === 0) {
    return `${packageName} (${severity}) is only present in the originating repository — no lateral exposure detected across ${totalRepositories} other monitored ${totalRepositories === 1 ? 'repository' : 'repositories'}.`
  }

  if (affectedRepositoryCount === 1) {
    return `${packageName} (${severity}) was also found in ${affectedRepositoryNames[0]}. Cross-repository exposure confirmed in 1 of ${totalRepositories} other monitored ${totalRepositories === 1 ? 'repository' : 'repositories'}.`
  }

  const names =
    affectedRepositoryNames.length <= 3
      ? affectedRepositoryNames.join(', ')
      : `${affectedRepositoryNames.slice(0, 2).join(', ')} and ${affectedRepositoryCount - 2} others`

  return `${packageName} (${severity}) affects ${affectedRepositoryCount} of ${totalRepositories} other monitored repositories: ${names}.`
}
